#!/bin/sh

set -x
# wait for start
sleep 5
echo "php-fpm: waiting for nginx to start.."
until pgrep 'nginx' >/dev/null 2>&1; do
  sleep 1
done

MEM=${PHP_MEM:=256M}


# copy rutorrent folder
if [ -d /downloads/rutorrent ] && [ ! -f /stop-copy-rutorrent ]; then
  mv /downloads/rutorrent /
  chown -R www-data:www-data /rutorrent
else
  install -o www-data -g www-data -m 777 -d /rutorrent
  touch /stop-copy-rtorrent
fi

touch /stop-copy-rutorrent

sed -i 's/memory_limit.*$/memory_limit = '$MEM'/g' /etc/php/fpm-php5.6/php.ini
sed -i -e 's/nobody/www-data/g' -e 's|127.0.0.1:9000|/run/php5-fpm.sock|g' /etc/php/fpm-php5.6/php-fpm.conf

#exec 2>&1
exec /usr/bin/php-fpm5.6 --nodaemonize -c /etc/php/fpm-php5.6 -y /etc/php/fpm-php5.6/php-fpm.conf 2>&1
exec s6-setuidgid nobody /usr/bin/php /var/www/update_daemon2.php
