#!/bin/sh

set -x

if [ ! -f /stop-ssh ]; then
  chsh -s /bin/sh sshd
  touch /run/sshd.pid
  chown sshd:sshd /run/sshd.pid
  busybox su -l -c "/usr/bin/ssh-keygen -A" sshd
  touch /stop-ssh
fi

# run
exec 2>&1
su-exec sshd /usr/sbin/sshd -D -e -p 21001
