#!/bin/sh

set -x

if [ ! -f /stop ]; then
  source /creds.txt
  echo "changing password for rtorrent user"
  echo rtorrent:$pass | chpasswd
  busybox su -l -c "/usr/bin/ssh-keygen -A" sshd
  touch /stop
fi

# run
exec 2>&1
su-exec sshd /usr/sbin/sshd -D -e -p 21001
