FROM ${IMAGE_PARENT}
MAINTAINER ${MAINTAINER}

ADD rootfs.tar /

ADD etc /etc

#RUN ldconfig && \
RUN chmod +x /etc/s6_finish_default && \
    ln -s /etc/s6_finish_default /etc/service/.s6-svscan/finish && \
    ln -s /etc/service/.s6-svscan /service

CMD ["/bin/s6-svscan", "-t0", "/service"]
